### ISSUE TITLE
Exposing more of the Rx to users

### ISSUE THREAD

**Issue by mikesol** [BennyWang/KBinding#12]
This is some _great_ stuff!  We've started playing around with it at Jongla (in Finland) and we really like the approach!

One thing that we'd love to see if possible is an API for OneWay binding that gets rid of the converter and the whole "one time" thing and functions purely on Rx. Internally this is happening in your code base (for example, you use Observable.take to implement one-time binding), but if the inside of the observable chain could be manipulated (for example, via "compose") then arbitrary mappings of bound variables could make their way down to the UI.

**Comment by BennyWang** [comment]
@mikesol  I'm very happy you are interested in KBinding, but I can not understand you very well.
1. You want remove converter parameter from OneWay binding? Am I right?
but I think converter is a very important feature for binding, because you can binding more things without create more properties.
2. You mean there have some bugs for OneTime binding in some situation cause binding not released after first time?
I didn't test too much for KBinding, It's open source, so if you can pull some requests, that will be great!

Sorry for my poor English If you can not understand my words.

**Comment by mikesol** [comment]
@BennyWang thanks for your reply!  Sorry, no, I wasn't clear.  OneTime binding is great!  Definitely keep it!
What would be nice is if _any_ Rx expression could be used instead of just OneTime (which is essentially `take(1)` in Rx).  For example, let's say that I wanted the binding to change three times but no more.  This can be expressed as:
`Observable.just(1,2,3,4).take(3).subscribe(/*do something*/)`

or if I wanted to take every 2nd value, I could do:
`Observable.just(1,2,3,4,5).sample(2).subscribe(/*do something*/)`

Currently, this more advanced binding is not possible within KBinding as you do not expose the Rx via the API.  What'd be nice is a way to do fancy Rx-style binding like what I'm talking about above.

**Comment by BennyWang** [comment]
@mikesol I got your point, a new feature. let me think about it. If you already have some idea about it, welcome to make a pull request.
